// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace YelpReviewML.Model
{
    public class ModelInput
    {
        [ColumnName("Sentiment"), LoadColumn(0)]
        public string Sentiment { get; set; }


        [ColumnName("Target"), LoadColumn(1)]
        public bool Target { get; set; }


    }
}
